[package]
name = "terrapin"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
gitoid = {git = "https://github.com/fkautz/gitbom-rs", branch = "boring", features = ["boring"]}
