[package]
name = "terrapin-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
structopt = "0.3"
terrapin = { path = "../terrapin" }
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
